Update plan_trabajo.md
ernestomancebo/intec pull request #104
Opened 2023-08-09 00:30 UTC by LaraPolancoAlejandro

Grupo 6

2023-08-09 23:42 UTC, Adamguerrero1720 reviewed
.

2023-08-10 01:06 UTC, ernestomancebo commented
¿Pueden compartir qué herramienta o librería utilizadan para minería de datos? Recuerden que debe de ser un tema **en tendencia**

2023-08-10 01:14 UTC, ernestomancebo commented
- Tiene conflictos. 
- ¿qué reservas realizará la aplicación a trabajar?

2023-08-10 02:20 UTC, Adamguerrero1720 commented
> * Tiene conflictos.
> 
>     * ¿qué reservas realizará la aplicación a trabajar?

- Conflicto resuelto.
- La app a trabajar realizará reservaciones para agendar citas en un negocio.
- Sobre el tema elegido para la presentación "Mineria de Datos" tenemos dudas las cuales mañana en clases las queremos debatir con usted para aclarar.

2023-08-10 03:14 UTC, ernestomancebo requested changes

2023-08-10 03:14 UTC, ernestomancebo commented on plan_trabajo.md
> +| Equipo 5 | Entity Framework           |   7    |       React                |   9    |               |
Estan borrando el proyecto del equipo 5.

2023-08-10 03:36 UTC, Adamguerrero1720 commented on plan_trabajo.md
> +| Equipo 5 | Entity Framework           |   7    |       React                |   9    |               |
Solucionado

2023-08-10 13:04 UTC, ernestomancebo approved these changes

2023-08-10 13:05 UTC, merged